### ISSUE TITLE
Craft Update Issue

### ISSUE THREAD

**Issue by superflausch** [sjelfull/craft3-autologin#3]
Hi there

I'm not sure if this is something on the plugin side or Craft itself. Unfortunately I'm getting this error when using the [new Craft update](https://docs.craftcms.com/v3/updating.html#updating-from-the-terminal) process they added in 3.0.38. Any ideas?

```
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: craft\console\Request::getUserIP()'

in /mypath/vendor/yiisoft/yii2/base/Component.php:300

Stack trace:
#0 /mypath/vendor/superbig/craft3-autologin/src/services/AutologinService.php(64): yii\base\Component->__call('getUserIP', Array)
#1 /mypath/vendor/superbig/craft3-autologin/src/Autologin.php(56): superbig\autologin\services\AutologinService->shouldLogin()
#2 /mypath/vendor/yiisoft/yii2/base/BaseObject.php(109): superbig\autologin\Autologin->init()
#3 /mypath/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#4 /mypath/vendor/craftcms/cms/src/base/Plugin.php(113): yii\base\Module->__construct('autologin', Object(craft\console\Application), Array)
#5 [internal function]: craft\base\Plugin->__construct('autologin', Object(craft\console\Application), Array)
#6 /mypath/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#7 /mypath/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('superbig\\autolo...', Array, Array)
#8 /mypath/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('superbig\\autolo...', Array, Array)
#9 /mypath/vendor/craftcms/cms/src/services/Plugins.php(789): yii\BaseYii::createObject(Array, Array)
#10 /mypath/vendor/craftcms/cms/src/services/Plugins.php(200): craft\services\Plugins->createPlugin('autologin', Array)
#11 /mypath/vendor/craftcms/cms/src/base/ApplicationTrait.php(1148): craft\services\Plugins->loadPlugins()
#12 /mypath/vendor/craftcms/cms/src/console/Application.php(64): craft\console\Application->_postInit()
#13 /mypath/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#14 /mypath/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#15 /mypath/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#16 /mypath/vendor/craftcms/cms/src/console/Application.php(53): yii\console\Application->__construct(Array)
#17 [internal function]: craft\console\Application->__construct(Array)
#18 /mypath/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#19 /mypath/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\console\\A...', Array, Array)
#20 /mypath/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\console\\A...', Array, Array)
#21 /mypath/vendor/craftcms/cms/bootstrap/bootstrap.php(252): yii\BaseYii::createObject(Array)
#22 /mypath/vendor/craftcms/cms/bootstrap/console.php(31): require('/Users/mollepas...')
#23 /mypath/craft(42): require('/Users/mollepas...')
#24 {main}

```

Thank you.

**Comment by sjelfull** [comment]
Thanks for reporting. New release is out that fixes this.
